version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            pytest tests/

  docker_build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t faezsq/invoicer:secure .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" > pass.txt
            cat pass.txt | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: Push Docker Image
          command: docker push faezsq/invoicer:secure

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - docker_build:
          requires:
            - build
